### PR TITLE
Update: generate and apply header values when key wrapping

### LINKED ISSUE #133: alg A128GCMKW encryption/decryption doesn't work
Hello @linuxwolf, 

i'm unable to get `A128GCMKW` alg compact JWE to work. Not sure if there's something obvious i'm doing wrong, i would appreciate your help. Should I be including `tag` and `iv` in the header(fields)? It encrypts without `tag` just fine. But i cannot get decrypt to work, even with the same key(store) as shown below.

```js
const jose = require('node-jose');
const format = 'compact';
const clientKS = jose.JWK.createKeyStore();
const secret = 'GfsT479VMy5ZZZPquadPbN3wKzaFGYo1CTkb0IFFzDNODLEAuC2GUV3QsTye3xNQ';
const alg = 'A128GCMKW';
const base64url = require('base64url');
const crypto = require('crypto');
const payload = JSON.stringify({ foo: 'bar' });
const fields = { alg };

const bufferderived = crypto.createHash('sha256')
      .update(secret)
      .digest()
      .slice(0, 128 / 8);

clientKS.add({
  k: base64url(bufferderived), kty: 'oct',
}).then(() => {
  fields.iv = base64url(crypto.randomBytes(12)); // doesn't encrypt without iv
  fields.tag = base64url(crypto.randomBytes(16)); // does encrypt without tag
  return jose.JWE.createEncrypt({ format, fields }, { key: clientKS.get(), reference: false })
    .update(payload)
    .final();
}).then((crypted) => {
  console.log(crypted)
  return jose.JWE.createDecrypt(clientKS.get()).decrypt(crypted);
}).then(console.log)

// > Error: no key found
```

### PR DESCRIPTION
**Pull request by linuxwolf**
Closes #133 

When wrapping keys in JWE, the algorithm can generate a missing value and it'll be applied to the JWE header(s).

For `A*GCMKW`:
* generate `"iv"` of 12 random bytes

For `PBES2-*`:
* generate `"p2s"` of 16 random bytes
* apply `"p2c"` of 8192

### CODE REVIEW

**Comment by linuxwolf** [comment]
@panva something is still broken then.  I thought I had tests in place, but I also had some hiccups bringin in master.  Will take a look, and make better tests for it.

**Comment by linuxwolf** [comment]
Right now, I see this as the thing that gets `node-jose` to `1.0.0`.

**Comment by linuxwolf** [comment]
@panva 

Latest commit on this PR should address the problems, and tests for it!  Would you confirm it meets your expectations?

**Comment by panva** [comment]
@linuxwolf yes, it's great! 👍

**Pull request merged**
