### PR TITLE
check instanceof ArrayBuffer with identity discontinuity

### PR DESCRIPTION
**Pull request by jinalkathiara**
Add identity discontinuity proof typechecking for ArrayBuffer

### CODE REVIEW

**Comment by linuxwolf** [comment]
Can you explain why this is necessary?  Frankly, I'd like a lot more proofs that this is required and doesn't unravel an onion of problems that are ultimately due to a buggy proxy implementation.

**Comment by jinalkathiara** [comment]
Reason for having this code is Aura locker service. We are building a salesforce -> cisco spark integration where cisco spark library is going to be considered as a 3rd party library. Because of prodsec requirement we are trying to isolate that library from main DOM and we are using Aura Locker Service for that approach. Look at this code how we are isolating it. 
https://github.com/forcedotcom/aura/blob/master/aura-resources/src/main/resources/aura/resources/lockerservice/safeEval.html

This way, we are evaluating 3rd party code under the iFrame and all the XHR and various other APIs are wrapped in a secure way. Given that some of the XHR response is of type ArrayBuffer, we might be in a situation where we will check instanceof ArrayBuffer cross window. 

Look at this link for cross window instanceof problem. This code is just fixing that and checking deep prototype. This is not some buggy proxy implementation.
http://tobyho.com/2011/01/28/checking-types-in-javascript/

**Comment by jinalkathiara** [comment]
@linuxwolf can you take a look one more time.

**Comment by jinalkathiara** [comment]
@linuxwolf - Do you need more info on this PR ? We are waiting for this PR to hit one of our project timeline, I will appreciate if you can comment on what is missing here.

**Comment by linuxwolf** [comment]
I've been on travel; just getting back to this.  Looping in @ianwremmel for his opinion.

If you need to isolate the library, then I think you really need to fully isolate it and pass JSON data back and forth instead of these hacks.  This is, at-best, a performance degradation on a routine that is called *a lot*; at worst, this code can cause failures if a type is ever introduced whose name is a superset of ArrayBuffer (e.g., "ArrayBufferView" or "MyArrayBuffer").

**Comment by jfparadis** [comment]
@linuxwolf 

Pease close this request, as we will resort to transpiration instead. Please accept our apologies for the disruption.

To answer your concerns:

- We were not satisfied with the performance of using JSON, which would have to be done at the entry of every function call. The overhead was much larger than with this technique. 
- The subset/superset issue mentioned above doesn't occur with our internal function, which transpiration allows us to do:
```
function sfdcInstanceOf(obj, type) {
  if (obj instanceof type) return true;
  var otherRealmType = typeToOtherRealmType && typeToOtherRealmType.get(type);
  return otherRealmType && obj instanceof otherRealmType;
}
```
- Of course there is a performance impact, but the cost only occurs on some specific objects, and is justifiable considering our security objectives:
See this [jsPerf](https://jsperf.com/instanceof-cross-realm/1)

**Pull request closed without merging**
