### PR TITLE
drop in replace base64url due to a vulnerability

### PR DESCRIPTION
**Pull request by panva**
Hi @linuxwolf,

the base64url package has a found [vulnerability](https://hackerone.com/reports/321687) currently reported by snyk and other tools. The report history shows attempts to contact the maintainer for a fix with no success since march 2017.

b64u is a drop-in replacement with the vulnerability fixed. It'd be great if you could fast-forward a patch release with this fix.

Also, there was a forgotten .only in the test suite.

### CODE REVIEW

**Comment by MeirionHughes** [comment]
maybe better to use `base64-url` as it has an engine requirement of 6+, which natively complains about `new buffer(1000, encoding)`. b64u still supported node 4+ and has less downloads/stars.

**Comment by panva** [comment]
b64u is not using `new Buffer`, so it's all good and has toBuffer which node-jose needs. Also support for lts/4 is needed

**Comment by MeirionHughes** [comment]
ah yes, I see; so many tabs open I must have been looking at something else. :D

**Comment by panva** [comment]
Is there something in the build that makes it fail in lts/8?

**Comment by linuxwolf** [comment]
Thanks @panva .  Looking at the error log from Travis-CI, it appears that `toBuffer` isn't coming back as a function in the browser.  Will have to do some investigation into why ...

**Comment by linuxwolf** [comment]
Taking a quick look, it looks like webpack is importing it as an es6 module, with a `default` instead of the rest of the methods.  The quick hack fix is:

```javascript
var impl = require("b64u");
if (impl.default) {
    impl = impl.default;
}
```

Will have to determine what the better fix is long term, though.

**Comment by linuxwolf** [comment]
@panva   Thanks very much!

I've added an issue (#180) to track getting rid of this `default` hack.

**Comment by panva** [comment]
Great thank you @linuxwolf, any chance for a patch release on the 0.11.x track?

**Comment by panva** [comment]
With the next patch I will, just so that my software uses more used/watched dependencies and with that ends up with cleaner dependency trees. For node-jose, your call.

**Comment by vladikoff** [comment]
@linuxwolf I also had the same problem as mentioned in https://github.com/cisco/node-jose/pull/179#issuecomment-389219128 

I'm leaning towards using base64url@3.0.0 but up to you

**Pull request merged**
