### PR TITLE
make more use of node crypto + more

### LINKED ISSUE #203: [question] Prevent nextTick from being used when possible
Would you accept a change where this block was not applied in `node` environment? Or could we get rid of it altogether (seems forge has some resolved IE-related issues about setImmediate).

```js
// Prevent nextTick from being used when possible
if ("function" === typeof setImmediate) {
  forge.util.setImmediate = forge.util.nextTick = function(callback) {
    setImmediate(callback);
  };
}
```

I'm tracing a lot of eventloop blocks to node-jose and forge and started a fork where I remove all the browser specifics and convert to async syntax, wanted to see where forge is needed, etc. (that's how i found RS256 and the like don't use native crypto at all, see #202). I could not verify this is the cause of the loop blocks but it's definitely not pretty.

In my fork i plan to put the browser and forge fallbacks back in place once i have node coverage up to 100% and then open a pr with a webpack build in place.

### LINKED ISSUE #210: Comparing input to string "object", is this correct?
I don't understand why the input is compared against the string "object". Was this intended to be typeof input === "object" ?

https://github.com/cisco/node-jose/blob/25040623607081197995b50e79d91b9d5a4c843c/lib/jws/verify.js#L69

### PR DESCRIPTION
**Pull request by panva**
- fixes correct jws verify input validation `typeof` check
- make use of native node crypto for AES-KW Key-Wrapping
- make use of native node crypto for RS signing
- make use of native node crypto for RSA-OAEP and RSA1_5 encryption
- make use of native node crypto for RSA-PSS
- make use of native node crypto for RSA1_5 decryption
- makes use of native node crypto for ECDSA
- removes setImmediate/nextTick IE workaround

I kindly ask for a review, especially for aa5a48d which as noted is inspired by another published implementation

with this in place the only use of `node-forge` in node lts/carbon is for converting keys between formats and `RSA-OAEP-256`

closes #203
fixes #210
closes #202

Note: can we remove non lts versions of node from travis? `RSASSA-PSS` support was added in `^6.12.0 || ^8.0.0`, never landed in 7

### CODE REVIEW

**Comment by panva** [comment]
benchmark comparison on the way

**Comment by panva** [comment]
Ran tests with the updated algorithm implementations against this PR and v1.0.0 with different concurrencies. Keystores were initialized before timing and the implementations were warmed up, so were the keys. Same repeating payloads.

concurrency=10 results with clear changes:

> decrypt RSA1_5 A128CBC-HS256 c10  **13.576ms** #214
> decrypt RSA1_5 A128CBC-HS256 c10 **299.746ms** v1.0.0

> encrypt RSA-OAEP A128CBC-HS256 c10  **9.089ms** #214
> encrypt RSA-OAEP A128CBC-HS256 c10 **27.659ms** v1.0.0

> encrypt RSA1_5 A128CBC-HS256 c10 **13.417ms** #214
> encrypt RSA1_5 A128CBC-HS256 c10 **25.360ms** v1.0.0

> sign ES256 c10   **6.249ms** #214
> sign ES256 c10 **116.366ms** v1.0.0

> sign PS256 c10  **12.677ms** #214
> sign PS256 c10 **324.104ms** v1.0.0

> sign RS256 c10  **12.703ms** #214
> sign RS256 c10 **329.936ms** v1.0.0

> verify ES256 c10   **7.242ms** #214
> verify ES256 c10 **150.170ms** v1.0.0

> verify PS256 c10  **1.218ms** #214
> verify PS256 c10 **13.529ms** v1.0.0


<details>
  <summary>Click to expand all results</summary>
<br/>

decrypt RSA-OAEP A128CBC-HS256 c1 2.597ms #214
decrypt RSA-OAEP A128CBC-HS256 c1 2.489ms v1.0.0

decrypt RSA-OAEP A128CBC-HS256 c10 13.248ms #214
decrypt RSA-OAEP A128CBC-HS256 c10 13.278ms v1.0.0

decrypt RSA-OAEP A128CBC-HS256 c100 117.189ms #214
decrypt RSA-OAEP A128CBC-HS256 c100 119.533ms v1.0.0

decrypt RSA-OAEP A128CBC-HS256 c1000 1182.967ms #214
decrypt RSA-OAEP A128CBC-HS256 c1000 1194.636ms v1.0.0

decrypt RSA1_5 A128CBC-HS256 c1  **2.688ms** #214
decrypt RSA1_5 A128CBC-HS256 c1 **54.785ms** v1.0.0

:exclamation: decrypt RSA1_5 A128CBC-HS256 c10  **13.576ms** #214
:exclamation: decrypt RSA1_5 A128CBC-HS256 c10 **299.746ms** v1.0.0

decrypt RSA1_5 A128CBC-HS256 c100  **124.494ms** #214
decrypt RSA1_5 A128CBC-HS256 c100 **2813.941ms** v1.0.0

decrypt RSA1_5 A128CBC-HS256 c1000  **1266.060ms** #214
decrypt RSA1_5 A128CBC-HS256 c1000 **27654.856ms** v1.0.0

encrypt RSA-OAEP A128CBC-HS256 c1 **2.023ms** #214
encrypt RSA-OAEP A128CBC-HS256 c1 **5.699ms** v1.0.0

:exclamation: encrypt RSA-OAEP A128CBC-HS256 c10  **9.089ms** #214
:exclamation: encrypt RSA-OAEP A128CBC-HS256 c10 **27.659ms** v1.0.0

encrypt RSA-OAEP A128CBC-HS256 c100  **93.704ms** #214
encrypt RSA-OAEP A128CBC-HS256 c100 **216.392ms** v1.0.0

encrypt RSA-OAEP A128CBC-HS256 c1000  **886.430ms** #214
encrypt RSA-OAEP A128CBC-HS256 c1000 **2176.609ms** v1.0.0

encrypt RSA1_5 A128CBC-HS256 c1 6.318ms #214
encrypt RSA1_5 A128CBC-HS256 c1 5.155ms v1.0.0

:exclamation: encrypt RSA1_5 A128CBC-HS256 c10 **13.417ms** #214
:exclamation: encrypt RSA1_5 A128CBC-HS256 c10 **25.360ms** v1.0.0

encrypt RSA1_5 A128CBC-HS256 c100  **97.054ms** #214
encrypt RSA1_5 A128CBC-HS256 c100 **240.705ms** v1.0.0

encrypt RSA1_5 A128CBC-HS256 c1000  **886.994ms** #214
encrypt RSA1_5 A128CBC-HS256 c1000 **2338.500ms** v1.0.0

sign ES256 c1  **1.380ms** #214
sign ES256 c1 **52.565ms** v1.0.0

:exclamation: sign ES256 c10   **6.249ms** #214
:exclamation: sign ES256 c10 **116.366ms** v1.0.0

sign ES256 c100  **63.131ms** #214
sign ES256 c100 **969.876ms** v1.0.0

sign ES256 c1000  **503.601ms** #214
sign ES256 c1000 **9572.963ms** v1.0.0

sign PS256 c1  **2.371ms** #214
sign PS256 c1 **57.043ms** v1.0.0

:exclamation: sign PS256 c10  **12.677ms** #214
:exclamation: sign PS256 c10 **324.104ms** v1.0.0

sign PS256 c100  **117.010ms** #214
sign PS256 c100 **2860.787ms** v1.0.0

sign PS256 c1000  **1134.764ms** #214
sign PS256 c1000 **27467.033ms** v1.0.0

sign RS256 c1  **2.601ms** #214
sign RS256 c1 **70.500ms** v1.0.0

:exclamation: sign RS256 c10  **12.703ms** #214
:exclamation: sign RS256 c10 **329.936ms** v1.0.0

sign RS256 c100  **120.476ms** #214
sign RS256 c100 **2818.754ms** v1.0.0

sign RS256 c1000  **1193.254ms** #214
sign RS256 c1000 **26972.657ms** v1.0.0

verify ES256 c1  **2.286ms** #214
verify ES256 c1 **44.823ms** v1.0.0

:exclamation: verify ES256 c10   **7.242ms** #214
:exclamation: verify ES256 c10 **150.170ms** v1.0.0

verify ES256 c100   **63.025ms** #214
verify ES256 c100 **1276.751ms** v1.0.0

verify ES256 c1000   **556.094ms** #214
verify ES256 c1000 **12712.695ms** v1.0.0

verify PS256 c1  **.580ms** #214
verify PS256 c1 **3.815ms** v1.0.0

:exclamation: verify PS256 c10  **1.218ms** #214
:exclamation: verify PS256 c10 **13.529ms** v1.0.0

verify PS256 c100 **11.799ms** #214
verify PS256 c100 **92.986ms** v1.0.0

verify PS256 c1000 **113.619ms** #214
verify PS256 c1000 **931.786ms** v1.0.0

verify RS256 c1 2.632ms #214
verify RS256 c1 3.084ms v1.0.0

verify RS256 c10 2.245ms #214
verify RS256 c10 1.825ms v1.0.0

verify RS256 c100 19.135ms #214
verify RS256 c100 14.221ms v1.0.0

verify RS256 c1000 132.833ms #214
verify RS256 c1000 114.280ms v1.0.0


</details>

**Comment by sunpeinju** [comment]
@linuxwolf eager to consume this fix, any publish plan? :)

**Comment by hannsjohn2007** [comment]
@sunpeinju for me I just install it like `npm i cisco/node-jose#master` it works fine :)

**Pull request merged**
